<a href="https://colab.research.google.com/github/Pujyalakshmi/MLDLS/blob/main/Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('Social_Network_Ads.csv')
print(dataset)

      User ID  Age  EstimatedSalary  Purchased
0    15624510   19            19000          0
1    15810944   35            20000          0
2    15668575   26            43000          0
3    15603246   27            57000          0
4    15804002   19            76000          0
..        ...  ...              ...        ...
395  15691863   46            41000          1
396  15706071   51            23000          1
397  15654296   50            20000          1
398  15755018   36            33000          0
399  15594041   49            36000          1

[400 rows x 4 columns]


In [ ]:
X = dataset.iloc[:,:3].values
Y = dataset.iloc[:,-1].values

In [ ]:
print(X.shape, Y.shape)

(400, 3) (400,)


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)
print(X_train.shape, X_test.shape)

(280, 3) (120, 3)


In [ ]:
#Logistic Regression

from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression()
logReg.fit(X_train, Y_train)

Y_pred = logReg.predict(X_test)
print(Y_test, Y_pred)

[0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 0 1 1 0
 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1
 0 0 1 0 0 1 1 1 1 1 1 0 1 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0
 1 0 0 0 0 1 0 1 1] [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0
 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1
 0 0 0 0 0 1 1 0 1 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
 0 0 0 0 0 0 1 0 0]


In [ ]:
from sklearn.metrics import  confusion_matrix, accuracy_score, precision_score, recall_score

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred)) 
print("Precision:\n", precision_score(Y_test, Y_pred, average=None))
print("Recall:\n", recall_score(Y_test, Y_pred, average = None))

Confusion Matrix:
 [[74  4]
 [18 24]]
Accuracy:
 0.8166666666666667
Precision:
 [0.80434783 0.85714286]
Recall:
 [0.94871795 0.57142857]


In [ ]:
#KNN Classifier

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)

Y_pred_knn = knn.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_knn))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_knn)) 

Confusion Matrix:
 [[70  8]
 [17 25]]
Accuracy:
 0.7916666666666666


In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier

dtc= DecisionTreeClassifier()
dtc.fit(X_train, Y_train)

Y_pred_dtc = dtc.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_dtc))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_dtc)) 

Confusion Matrix:
 [[70  8]
 [ 5 37]]
Accuracy:
 0.8916666666666667


In [ ]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc.fit(X_train, Y_train)

Y_pred_rfc = rfc.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_rfc))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_rfc))

Confusion Matrix:
 [[69  9]
 [ 3 39]]
Accuracy:
 0.9
